### ISSUE TITLE
Add `@_exported import`

### ISSUE THREAD

**Issue by hstdt** [shaps80/SwiftUIBackports#32]
*Have you read the [Contributing Guidelines](https://github.com/shaps80/.github/blob/master/CONTRIBUTING.md)?*
Yes

## Describe the feature
Since SwiftUIBackports is based on SwiftUI, `@_exported import SwiftUI` is appropriate. No necessary to import SwiftUI after imported SwiftUIBackports.

## Is your feature request related to a problem? 
No

## Proposed solution

Add `@_exported import` to Backport.swift

https://github.com/hstdt/SwiftUIBackports/blob/3fd863242bedbcb4ccf21e0d6503d489c3f36bd6/Sources/SwiftUIBackports/Backport.swift#L4

**Comment by shaps80** [comment]
Actually I considered this but intentionally left it out.

If you try that you’ll notice a lot of the time Xcode previews stop working in any file that doesn’t explicitly include `import SwiftUI`

Its really annoying but until they fix/allow that I won’t be including since I don’t want to break (with no helpful feedback) any previews in your project ;)
