### ISSUE TITLE
UIHostingConfiguration

### ISSUE THREAD

**Issue by K1NXZ** [shaps80/SwiftUIBackports#4]
Any plans to backport [UIHostingConfiguration](https://developer.apple.com/documentation/SwiftUI/UIHostingConfiguration) added in iOS 16 would be great for the beginning to configure cells with SwiftUI.

**Comment by shaps80** [comment]
I haven’t looked deeply into the `UIHostingConfiguration` yet but I imagine that might be difficult to backport actually. It requires a lot more understanding and access (I think) to the underlying SwiftUI components. But I’ll definitely explore it.

As for Lazy Stacks, its not obvious how best to achieve this, however I am looking at alternatives. For example I think it might be possible to provide a backport fo the new Layout APIs which would potentially open the door for creating this kind of thing, as well as any other layouts.

My other idea was to create a new type (not a backport) that wraps `UICollectionView` and provides a really nice SwiftUI API that would enable lazy stacks and other implementations. I’ve actually been working on this one prior to WWDC so I may explore this a little more. The API is really nice and its quite promising. This would be a separate library of course, but I’ll let you know when I’ve explored this a little more 👍🏻.

**Comment by shaps80** [comment]
I'll strikeout the above as I completely mis-remembered what UIHostingConfiguration was.

I did actually see this mentioned at WWDC I recall now, and its pretty nice to make it easier for UIKit users to bring SwiftUI into their code. However, that's not exactly the purpose of this library. This feels more like I'd be back porting UIKit in order to support this. 

That being said, I am (as mentioned above) working on something related to UICollectionView that _does_ require me to wrap SwiftUI view's in cells. So if there is even a _lightweight_ version of this that could be useful in this library, I'll include it and let you know 👍

**Comment by shaps80** [comment]
Good news @K1NXZ, I managed to get most of this working already. I have intentionally left out much of the `UIContentConfiguration` APIs since they're only useful if we also backport the whole iOS 14+ API they introduced for configuring cells, which would be a lot of effort.

But I think this still provides a useful and familiar API that should make it just as easy to integrate SwiftUI into cells.

<img width="1094" alt="Screenshot 2022-07-01 at 01 37 59" src="https://user-images.githubusercontent.com/251310/176800576-1b7badb8-804f-4701-94dd-f9d89c18baf1.png">

**Comment by shaps80** [comment]
I will test this more thoroughly for a while, but it's looking quite promising. If you have time, I'd love if you could test it out on the branch [`hosting`](https://github.com/shaps80/SwiftUIBackports/tree/hosting)

**Comment by shaps80** [comment]
<img width="567" alt="Screenshot 2022-07-01 at 02 18 39" src="https://user-images.githubusercontent.com/251310/176803701-8323b456-7c37-4dac-bb40-e0ba18924ea0.png">

Its looking good so far 👍

**Comment by shaps80** [comment]
Merged and released #6 – v1.1.0

**Comment by K1NXZ** [comment]
Looking great! Unfortunately I didn't have time to test it out yet. I will look into it ASAP.

**Comment by K1NXZ** [comment]
> Looking great! Unfortunately I didn't have time to test it out yet. I will look into it ASAP.

Just tested it, its working pretty well! Good job.

**Comment by shaps80** [comment]
Good to hear! Any issues please raise so I can take a look. Thanks!

**Comment by lukeredpath** [comment]
@shaps80 do you know how easy it would be to get this working with `UITableViewCell` too?

**Comment by shaps80** [comment]
> @shaps80 do you know how easy it would be to get this working with `UITableViewCell` too?

@lukeredpath I don't imagine it's very different at all. If you 'copy' the existing implementation I've provided for collection view you are welcome to contribute to the library.

I will eventually get around to it myself, but I don't have time atm.
