### ISSUE TITLE
Can we back port iOS17 Observation?

### ISSUE THREAD

**Issue by skywalkerlw** [shaps80/SwiftUIBackports#67]
Here is an demo project : https://github.com/onevcat/ObservationBP

Can we include it in your project?

**Comment by shaps80** [comment]
Hey thanks for reaching out! I wasn't aware of that implementation but I've also back ported it already (mostly) however considering how complex it is, I'm currently using it a live production application to sandbox test it. 

That said, its impossible AFAICT to fully backport with all functionality and so it would feel 'incomplete'.

Therefore at this stage I'm not willing to include it. I checked the link above and see they've solved some of the issues in different ways but at this point that wouldn't be a backport, rather an alternative (albeit more available) alternative.

I'll be working on this longer term so if I can find some more elegant solutions I may be able to include something, but for the moment its looking unlikely I'm afraid.

**Comment by DandyLyons** [comment]
For consideration: Pointfree's Perception is another option for backporting Observation. 

https://www.pointfree.co/blog/posts/129-perception-a-back-port-of-observable

**Comment by shaps80** [comment]
I am aware and this is mostly still based on other backports with the same implementation, or at least approach.

However its not a 1-2-1 and I generally have avoided solutions that differ from the original, since its more involved for the user to migrate later on, requires more documentation (that no one reads), etc etc

So I won't be included this I'm afraid, but thank you for the comment.
